apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q04xe425m-nodejs
  janus-idp.io/tekton: q04xe425m-nodejs
  backstage.io/kubernetes-id: q04xe425m-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q04xe425m-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
